print("Python Poetry: The Road Not Taken by Robert Frost\nThis poem is an example of formal verse, a narrative of four stanzas consisting of five lines each. Each verse follows the rhyme scheme of ABAAB.")
import datetime
today = datetime.date.today()
print(today)
print(
    "Welcome to the Poem Generator.\nI need to a few words from you to complete the poem."
)
import time

color = input("Enter a color: ")
print("\tTwo roads divereged in a " + color + " wood.")
time.sleep(5)
name = input("Enter a name: ")
print("\tAnd sorry " + name + " could not travel both")
time.sleep(5)
print("\tAnd be one traveler, long " + name + " stood")
time.sleep(5)
print("\tAnd looked down one as far as " + name + " could")
time.sleep(5)
print("\tTo where it bent in the undergrowth;")
time.sleep(3)
print("\t...")
time.sleep(3)
action = input("Enter a present participle: ")
print("\t" + name + " shall be " + action + " this with a sigh")
time.sleep(5)
print("\tSonewhere ages and ages hence:")
time.sleep(5)
print("\tTwo roads diverged in a wood, and " + name + "--")
time.sleep(5)
print("\t" + name + " took the one less traveled by,")
time.sleep(5)
print("\tAnd that has made all the difference.")
print("Now you have your own poem about the choices you make in life.")
